"""empty message

Revision ID: 4ce25540ec63
Revises: f575424076f8
Create Date: 2022-03-19 16:25:49.173373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce25540ec63'
down_revision = 'f575424076f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
