"""empty message

Revision ID: 8b3ff342d2ea
Revises: 
Create Date: 2022-04-04 19:29:35.306385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3ff342d2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('pregunta1', sa.String(length=250), nullable=False),
    sa.Column('pregunta2', sa.String(length=250), nullable=False),
    sa.Column('foto_carnet', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=250), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('regiones_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regiones_id'], ['regiones.id'], ),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('githubuser', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=150), nullable=False),
    sa.Column('comentario', sa.String(length=400), nullable=False),
    sa.Column('clientes_id', sa.Integer(), nullable=False),
    sa.Column('profesionales_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientes_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['profesionales_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidades_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=150), nullable=False),
    sa.Column('profesionales_id', sa.Integer(), nullable=True),
    sa.Column('habilidades_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habilidades_id'], ['habilidades.id'], ),
    sa.ForeignKeyConstraint(['profesionales_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habilidades_tecnicas')
    op.drop_table('evaluaciones')
    op.drop_table('profesionales')
    op.drop_table('clientes')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('regiones')
    op.drop_table('habilidades')
    # ### end Alembic commands ###
