"""empty message

Revision ID: b46ad03006f5
Revises: 4ce25540ec63
Create Date: 2022-03-19 16:42:37.437739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46ad03006f5'
down_revision = '4ce25540ec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nombre_institucion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nombre_institucion',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
