"""empty message

Revision ID: f575424076f8
Revises: f11c7dfdc3a0
Create Date: 2022-03-19 16:07:33.895285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f575424076f8'
down_revision = 'f11c7dfdc3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'direccion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.alter_column('users', 'titulo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'titulo',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'direccion',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'telefono',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
